
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CONTAINS DIFF EQUALS EXCLUDES GET INTERSECT NAME OR STAT UNION URLdefaut : assign\n    | getassign : NAME EQUALS getget : GET URL \n    | GET URL contrainte_liee\n    | GET URL contraintecontrainte_liee : contrainte_liee AND contrainte \n    | contrainte_liee OR contrainte\n    | contraintecontrainte : CONTAINS NAME\n    | EXCLUDES NAME'
    
_lr_action_items = {'NAME':([0,11,12,],[4,15,16,]),'GET':([0,6,],[5,5,]),'$end':([1,2,3,7,8,9,10,15,16,17,18,],[0,-1,-2,-4,-3,-5,-6,-10,-11,-7,-8,]),'EQUALS':([4,],[6,]),'URL':([5,],[7,]),'CONTAINS':([7,13,14,],[11,11,11,]),'EXCLUDES':([7,13,14,],[12,12,12,]),'AND':([9,10,15,16,17,18,],[13,-9,-10,-11,-7,-8,]),'OR':([9,10,15,16,17,18,],[14,-9,-10,-11,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'defaut':([0,],[1,]),'assign':([0,],[2,]),'get':([0,6,],[3,8,]),'contrainte_liee':([7,],[9,]),'contrainte':([7,13,14,],[10,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> defaut","S'",1,None,None,None),
  ('defaut -> assign','defaut',1,'p_defaut','TP4_Langages_Grammaire.py',65),
  ('defaut -> get','defaut',1,'p_defaut','TP4_Langages_Grammaire.py',66),
  ('assign -> NAME EQUALS get','assign',3,'p_assign','TP4_Langages_Grammaire.py',69),
  ('get -> GET URL','get',2,'p_get','TP4_Langages_Grammaire.py',72),
  ('get -> GET URL contrainte_liee','get',3,'p_get','TP4_Langages_Grammaire.py',73),
  ('get -> GET URL contrainte','get',3,'p_get','TP4_Langages_Grammaire.py',74),
  ('contrainte_liee -> contrainte_liee AND contrainte','contrainte_liee',3,'p_contrainte_liee','TP4_Langages_Grammaire.py',78),
  ('contrainte_liee -> contrainte_liee OR contrainte','contrainte_liee',3,'p_contrainte_liee','TP4_Langages_Grammaire.py',79),
  ('contrainte_liee -> contrainte','contrainte_liee',1,'p_contrainte_liee','TP4_Langages_Grammaire.py',80),
  ('contrainte -> CONTAINS NAME','contrainte',2,'p_contrainte','TP4_Langages_Grammaire.py',84),
  ('contrainte -> EXCLUDES NAME','contrainte',2,'p_contrainte','TP4_Langages_Grammaire.py',85),
]
